### ISSUE TITLE
Code implementation for Polyvore Outfit Dataset

### ISSUE THREAD

**Issue by DrFV** [rxtan2/Learning-Similarity-Conditions#14]
Thanks for your work! But for the Polyvore dataset, how do you configure the input for the weight branch and how do you obtain the corresponding weight for a single image during testing? Could you provide a code version for the Polyvore dataset, please?

**Comment by rxtan2** [comment]
Hi DrFV, thank you very much for your interest. It has been a while since I took a look at this but I think this should be the file: https://drive.google.com/file/d/1YUbQDU63nfjyT4GoUxO6LglQhUFRb2f1/view?usp=drive_link

However, this is based on the much older version of pytorch and python, so it is likely that newer hardware and / or cuda and torch versions will lead to differences in the training process. I currently do not have cycles to get it working with the newer torch versions but I can try to help resolve any possible issues.  Please feel free to email me  at rxtan@bu.edu if so.

**Comment by DrFV** [comment]
> Hi DrFV, thank you very much for your interest. It has been a while since I took a look at this but I think this should be the file: https://drive.google.com/file/d/1YUbQDU63nfjyT4GoUxO6LglQhUFRb2f1/view?usp=drive_link
> 
> However, this is based on the much older version of pytorch and python, so it is likely that newer hardware and / or cuda and torch versions will lead to differences in the training process. I currently do not have cycles to get it working with the newer torch versions but I can try to help resolve any possible issues. Please feel free to email me at [rxtan@bu.edu](mailto:rxtan@bu.edu) if so.

Thanks for your replying! It's very helpful.

**Comment by rxtan2** [comment]
It's my pleasure!
